// Монгол улсын аймаг, сумдын дэлгэрэнгүй мэдээлэл
export const aimags = [
  {
    value: "ulaanbaatar",
    label: "Улаанбаатар",
    sums: [
      { value: "baganuur", label: "Багануур" },
      { value: "bagakhangai", label: "Багахангай" },
      { value: "bayangol", label: "Баянгол" },
      { value: "bayanzurkh", label: "Баянзүрх" },
      { value: "nalaikh", label: "Налайх" },
      { value: "songinokhairkhan", label: "Сонгино Хайрхан" },
      { value: "sukhbaatar", label: "Сүхбаатар" },
      { value: "khan-uul", label: "Хан-Уул" },
      { value: "chingeltei", label: "Чингэлтэй" },
    ],
  },
  {
    value: "arkhangai",
    label: "Архангай",
    sums: [
      { value: "battsengel", label: "Батцэнгэл" },
      { value: "bulgan-arkhangai", label: "Булган" },
      { value: "jargalant-arkhangai", label: "Жаргалант" },
      { value: "ikhtamir", label: "Ихтамир" },
      { value: "ugii-nuur", label: "Өгийнуур" },
      { value: "ulziit-arkhangai", label: "Өлзийт" },
      { value: "undur-ulaan", label: "Өндөр-Улаан" },
      { value: "tariat", label: "Тариат" },
      { value: "tovshruuleh", label: "Төвшрүүлэх" },
      { value: "khairkhan-arkhangai", label: "Хайрхан" },
      { value: "khangai", label: "Хангай" },
      { value: "khashat", label: "Хашаат" },
      { value: "khotont", label: "Хотонт" },
      { value: "tsahir", label: "Цахир" },
      { value: "tsenkher", label: "Цэнхэр" },
      { value: "tsetserleg-sum", label: "Цэцэрлэг сум" },
      { value: "chuluut", label: "Чулуут" },
      { value: "erdenemandal", label: "Эрдэнэмандал" },
      { value: "erdenebulgan", label: "Эрдэнэбулган (Цэцэрлэг хот)" },
    ],
  },
  {
    value: "bayan-ulgii",
    label: "Баян-Өлгий",
    sums: [
      { value: "ulgii", label: "Өлгий хот" },
      { value: "altai-bayan-ulgii", label: "Алтай" },
      { value: "altantsugts", label: "Алтанцөгц" },
      { value: "bayannuur-bayan-ulgii", label: "Баяннуур" },
      { value: "bugat-bayan-ulgii", label: "Бугат" },
      { value: "bulgan-bayan-ulgii", label: "Булган" },
      { value: "buyant", label: "Буянт" },
      { value: "deluun", label: "Дэлүүн" },
      { value: "nogoonnuur", label: "Ногооннуур" },
      { value: "sagsai", label: "Сагсай" },
      { value: "tsagaannuur", label: "Цагааннуур" },
      { value: "tolbo", label: "Толбо" },
      { value: "ulaankhus", label: "Улаанхус" },
      { value: "tsengel", label: "Цэнгэл" },
    ],
  },
  {
    value: "bayankhongor",
    label: "Баянхонгор",
    sums: [
      { value: "bayankhongor-city", label: "Баянхонгор" },
      { value: "baatsagaan", label: "Баацагаан" },
      { value: "bayanbulgan", label: "Баянбулаг" },
      { value: "bayangovi", label: "Баянговь" },
      { value: "bayanlig", label: "Баянлиг" },
      { value: "bayan-ovoo-bayankhongor", label: "Баян-Овоо" },
      { value: "bayan-undur-bayankhongor", label: "Баян-Өндөр" },
      { value: "bayantsagaan", label: "Баянцагаан" },
      { value: "bogd-bayankhongor", label: "Богд" },
      { value: "bombogor", label: "Бөмбөгөр" },
      { value: "buutsagaan", label: "Бууцагаан" },
      { value: "galuut", label: "Галуут" },
      { value: "gurvanbulgan", label: "Гурванбулаг" },
      { value: "jargalant-bayankhongor", label: "Жаргалант" },
      { value: "jinst", label: "Жинст" },
      { value: "zag", label: "Заг" },
      { value: "ulziit-bayankhongor", label: "Өлзийт" },
      { value: "khureemaral", label: "Хүрээмарал" },
      { value: "shinejinst", label: "Шинэжинст" },
      { value: "erdenetsogt", label: "Эрдэнэцогт" },
    ],
  },
  {
    value: "bulgan",
    label: "Булган",
    sums: [
      { value: "bulgan-city", label: "Булган" },
      { value: "bayan-agt", label: "Баян-Агт" },
      { value: "bayannuur-bulgan", label: "Баяннуур" },
      { value: "bugat-bulgan", label: "Бугат" },
      { value: "burekhangai", label: "Бүрэгхангай" },
      { value: "gurvanbulgan-bulgan", label: "Гурванбулаг" },
      { value: "dashinchilen", label: "Дашинчилэн" },
      { value: "mogod", label: "Могод" },
      { value: "orkhon-bulgan", label: "Орхон" },
      { value: "rashaant", label: "Рашаант" },
      { value: "saikhan-bulgan", label: "Сайхан" },
      { value: "selenge-bulgan", label: "Сэлэнгэ" },
      { value: "teshig", label: "Тэшиг" },
      { value: "khangal", label: "Хангал" },
      { value: "khishig-undur", label: "Хишиг-Өндөр" },
      { value: "khutag-undur", label: "Хутаг-Өндөр" },
    ],
  },
  {
    value: "govi-altai",
    label: "Говь-Алтай",
    sums: [
      { value: "altai-govi-altai", label: "Алтай" },
      { value: "bayan-uul-govi-altai", label: "Баян-Уул" },
      { value: "biger", label: "Бигэр" },
      { value: "bugat-govi-altai", label: "Бугат" },
      { value: "darvi-govi-altai", label: "Дарви" },
      { value: "delger", label: "Дэлгэр" },
      { value: "esunbulag", label: "Есөнбулаг" },
      { value: "jargalan", label: "Жаргалан" },
      { value: "taishir", label: "Тайшир" },
      { value: "tonkhil", label: "Тонхил" },
      { value: "tugrug", label: "Төгрөг" },
      { value: "khaliun", label: "Халиун" },
      { value: "khukhmorit", label: "Хөхморьт" },
      { value: "tsogt", label: "Цогт" },
      { value: "tseel", label: "Цээл" },
      { value: "chandmani-govi-altai", label: "Чандмань" },
      { value: "sharga", label: "Шарга" },
      { value: "erdene-govi-altai", label: "Эрдэнэ" },
    ],
  },
  {
    value: "govisumber",
    label: "Говьсүмбэр",
    sums: [
      { value: "sumber", label: "Сүмбэр" },
      { value: "bayantal", label: "Баянтал" },
      { value: "shiveegovi", label: "Шивээговь" },
    ],
  },
  {
    value: "darkhan-uul",
    label: "Дархан-Уул",
    sums: [
      { value: "darkhan", label: "Дархан" },
      { value: "khongor", label: "Хонгор" },
      { value: "orkhon-darkhan", label: "Орхон" },
      { value: "sharyngol", label: "Шарынгол" },
    ],
  },
  {
    value: "dornogovi",
    label: "Дорноговь",
    sums: [
      { value: "sainshand", label: "Сайншанд" },
      { value: "airag", label: "Айраг" },
      { value: "altanshiree", label: "Алтанширээ" },
      { value: "dalanjargalan", label: "Даланжаргалан" },
      { value: "delgerekh", label: "Дэлгэрэх" },
      { value: "zamyn-uud", label: "Замын-Үүд" },
      { value: "ikhkhet", label: "Иххэт" },
      { value: "mandakh", label: "Мандах" },
      { value: "urgun", label: "Өргөн" },
      { value: "saikhandulan", label: "Сайхандулаан" },
      { value: "ulaanbadrakh", label: "Улаанбадрах" },
      { value: "khatanbulag", label: "Хатанбулаг" },
      { value: "khovsgol-dornogovi", label: "Хөвсгөл" },
      { value: "erdene-dornogovi", label: "Эрдэнэ" },
    ],
  },
  {
    value: "dornod",
    label: "Дорнод",
    sums: [
      { value: "kherlen", label: "Хэрлэн" },
      { value: "bayandun", label: "Баяндун" },
      { value: "bayantumen", label: "Баянтүмэн" },
      { value: "bayan-uul-dornod", label: "Баян-Уул" },
      { value: "bulgan-dornod", label: "Булган" },
      { value: "gurvanzagal", label: "Гурванзагал" },
      { value: "dashbalbar", label: "Дашбалбар" },
      { value: "matad", label: "Матад" },
      { value: "sergelen-dornod", label: "Сэргэлэн" },
      { value: "khalkhgol", label: "Халхгол (Сүмбэр)" },
      { value: "kholonbuir", label: "Хөлөнбуйр" },
      { value: "tsagaan-ovoo", label: "Цагаан-Овоо" },
      { value: "chuluunkhoroot", label: "Чулуунхороот (Эрээнцав)" },
      { value: "choibalsan", label: "Чойбалсан" },
    ],
  },
  {
    value: "dundgovi",
    label: "Дундговь",
    sums: [
      { value: "mandalgovi", label: "Мандалговь (аймгийн төв)" },
      { value: "adaatsag", label: "Адаацаг" },
      { value: "bayanjargalan", label: "Баянжаргалан" },
      { value: "govi-ugtaal", label: "Говь-Угтаал" },
      { value: "gurvansaikhan", label: "Гурвансайхан" },
      { value: "delgerkhangai", label: "Дэлгэрхангай" },
      { value: "delgertsogt-dundgovi", label: "Дэлгэрцогт" },
      { value: "deren", label: "Дэрэн" },
      { value: "luus", label: "Луус" },
      { value: "ulziit-dundgovi", label: "Өлзийт" },
      { value: "undurshil", label: "Өндөршил" },
      { value: "saikhan-ovoo-dundgovi", label: "Сайхан-Овоо" },
      { value: "khuld", label: "Хулд" },
      { value: "tsagaandelger", label: "Цагаандэлгэр" },
      { value: "erdenedalai", label: "Эрдэнэдалай" },
    ],
  },
  {
    value: "zavkhan",
    label: "Завхан",
    sums: [
      { value: "uliastai", label: "Улиастай" },
      { value: "aldarkhaan", label: "Алдархаан" },
      { value: "asgat-zavkhan", label: "Асгат" },
      { value: "bayantes", label: "Баянтэс" },
      { value: "bayankhairkhan", label: "Баянхайрхан" },
      { value: "durvuljin", label: "Дөрвөлжин" },
      { value: "zavkhanmandal", label: "Завханмандал" },
      { value: "ider", label: "Идэр" },
      { value: "ikh-uul-zavkhan", label: "Их-Уул" },
      { value: "numrug", label: "Нөмрөг" },
      { value: "otgon", label: "Отгон" },
      { value: "santmargats", label: "Сантмаргац" },
      { value: "songino-zavkhan", label: "Сонгино" },
      { value: "tosontsengel", label: "Тосонцэнгэл" },
      { value: "tudevtei", label: "Түдэвтэй" },
      { value: "telmen", label: "Тэлмэн" },
      { value: "tes-zavkhan", label: "Тэс" },
      { value: "urgamal", label: "Ургамал" },
      { value: "tsagaankhairkhan", label: "Цагаанхайрхан" },
      { value: "tsagaanchuluut", label: "Цагаанчулуут" },
      { value: "tsetsen-uul", label: "Цэцэн-Уул" },
      { value: "shiluustei", label: "Шилүүстэй" },
      { value: "erdenekhairkhan", label: "Эрдэнэхайрхан" },
      { value: "yaruu", label: "Яруу" },
    ],
  },
  {
    value: "orkhon",
    label: "Орхон",
    sums: [
      { value: "erdenet", label: "Эрдэнэт" },
      { value: "bayan-undur-orkhon", label: "Баян-Өндөр" },
      { value: "jargalant-orkhon", label: "Жаргалант" },
    ],
  },
  {
    value: "uvurkhangai",
    label: "Өвөрхангай",
    sums: [
      { value: "arvaikheer", label: "Арвайхээр-Аймгийн төв" },
      { value: "baruunbayan-ulaan", label: "Баруунбаян-Улаан" },
      { value: "bat-ulzii", label: "Бат-Өлзий" },
      { value: "bayangol-uvurkhangai", label: "Баянгол" },
      { value: "bayan-undur-uvurkhangai", label: "Баян-Өндөр" },
      { value: "bogd-uvurkhangai", label: "Богд" },
      { value: "burd", label: "Бүрд" },
      { value: "guchin-us", label: "Гучин-Ус" },
      { value: "kharkhorin", label: "Хархорин" },
      { value: "khairhandulaan", label: "Хайрхандулаан" },
      { value: "khujirt", label: "Хужирт" },
      { value: "nariinteel", label: "Нарийнтээл" },
      { value: "ulziit-uvurkhangai", label: "Өлзийт" },
      { value: "sant-uvurkhangai", label: "Сант" },
      { value: "taragt", label: "Тарагт" },
      { value: "tugrug-uvurkhangai", label: "Төгрөг" },
      { value: "uyanga", label: "Уянга" },
      { value: "yesonzuil", label: "Есөнзүйл" },
      { value: "zuunbayan-ulaan", label: "Зүүнбаян-Улаан" },
    ],
  },
  {
    value: "umnugovi",
    label: "Өмнөговь",
    sums: [
      { value: "dalanzadgad", label: "Даланзадгад" },
      { value: "bayandalai", label: "Баяндалай" },
      { value: "bayan-ovoo-umnugovi", label: "Баян-Овоо" },
      { value: "bulgan-umnugovi", label: "Булган" },
      { value: "gurvantes", label: "Гурвантэс" },
      { value: "mandal-ovoo", label: "Мандал-Овоо" },
      { value: "manlai", label: "Манлай" },
      { value: "noyon", label: "Ноён" },
      { value: "nomgon", label: "Номгон" },
      { value: "sevrei", label: "Сэврэй" },
      { value: "khanbogd", label: "Ханбогд" },
      { value: "khankhongor", label: "Ханхонгор" },
      { value: "khurmen", label: "Хүрмэн" },
      { value: "tsogt-ovoo", label: "Цогт-Овоо" },
      { value: "tsogttsetsii", label: "Цогтцэций (Тавантолгой)" },
    ],
  },
  {
    value: "sukhbaatar-aimag",
    label: "Сүхбаатар",
    sums: [
      { value: "baruun-urt", label: "Баруун-Урт" },
      { value: "asgat-sukhbaatar", label: "Асгат" },
      { value: "bayandelger-sukhbaatar", label: "Баяндэлгэр" },
      { value: "dariganga", label: "Дарьганга" },
      { value: "munkhkhaan", label: "Мөнххаан" },
      { value: "naran", label: "Наран" },
      { value: "ongon", label: "Онгон" },
      { value: "sukhbaatar-sukhbaatar", label: "Сүхбаатар" },
      { value: "tuvshinshiree", label: "Түвшинширээ" },
      { value: "tumentsogt", label: "Түмэнцогт" },
      { value: "uulbayan", label: "Уулбаян" },
      { value: "khalzan", label: "Халзан" },
      { value: "erdenetsagaan", label: "Эрдэнэцагаан" },
    ],
  },
  {
    value: "selenge",
    label: "Сэлэнгэ",
    sums: [
      { value: "sukhbaatar-city", label: "Сүхбаатар" },
      { value: "altanbulag-selenge", label: "Алтанбулаг" },
      { value: "baruunburen", label: "Баруунбүрэн" },
      { value: "bayangol-selenge", label: "Баянгол" },
      { value: "yeruul", label: "Ерөө" },
      { value: "javkhlant-selenge", label: "Жавхлант" },
      { value: "zuunburen", label: "Зүүнбүрэн" },
      { value: "mandal-selenge", label: "Мандал" },
      { value: "orkhon-selenge", label: "Орхон" },
      { value: "orkhontuul", label: "Орхонтуул" },
      { value: "saikhan-selenge", label: "Сайхан" },
      { value: "sant-selenge", label: "Сант" },
      { value: "tushig", label: "Түшиг" },
      { value: "khuder", label: "Хүдэр" },
      { value: "khushaat", label: "Хушаат" },
      { value: "tsagaannuur-selenge", label: "Цагааннуур" },
      { value: "shaamar", label: "Шаамар" },
    ],
  },
  {
    value: "tuv",
    label: "Төв",
    sums: [
      { value: "zuunmod", label: "Зуунмод" },
      { value: "altanbulag-tuv", label: "Алтанбулаг" },
      { value: "argalant", label: "Аргалант" },
      { value: "arkhust", label: "Архуст" },
      { value: "bayan-tuv", label: "Баян" },
      { value: "batsumber", label: "Батсүмбэр" },
      { value: "bayandelger-tuv", label: "Баяндэлгэр" },
      { value: "bayanjargalan-tuv", label: "Баянжаргалан" },
      { value: "bayan-unjuul", label: "Баян-Өнжүүл" },
      { value: "bayankhairkhan-tuv", label: "Баянхангай" },
      { value: "bayantsagaan-tuv", label: "Баянцагаан" },
      { value: "bayantsogtt", label: "Баянцогт" },
      { value: "bayanchandmani", label: "Баянчандмань" },
      { value: "bornuur", label: "Борнуур" },
      { value: "buren-tuv", label: "Бүрэн" },
      { value: "delgerkhaan", label: "Дэлгэрхаан" },
      { value: "jargalant-tuv", label: "Жаргалант" },
      { value: "zaamar", label: "Заамар" },
      { value: "lun", label: "Лүн" },
      { value: "mungunmorit", label: "Мөнгөнморьт" },
      { value: "undurshireet", label: "Өндөрширээт" },
      { value: "sergelen-tuv", label: "Сэргэлэн" },
      { value: "sumber-tuv", label: "Сүмбэр" },
      { value: "ugtaaltsaidam", label: "Угтаалцайдам" },
      { value: "tseel-tuv", label: "Цээл" },
      { value: "erdene-tuv", label: "Эрдэнэ" },
      { value: "erdenesant", label: "Эрдэнэсант" },
    ],
  },
  {
    value: "uvs",
    label: "Увс",
    sums: [
      { value: "ulaangom", label: "Улаангом" },
      { value: "baruunturuun", label: "Баруунтуруун" },
      { value: "bukhmurun", label: "Бөхмөрөн" },
      { value: "davst", label: "Давст" },
      { value: "zavkhan-uvs", label: "Завхан" },
      { value: "zuungovi", label: "Зүүнговь" },
      { value: "zuunkhangai", label: "Зүүнхангай" },
      { value: "malchin", label: "Малчин" },
      { value: "naranbulag-uvs", label: "Наранбулаг" },
      { value: "ulgii-uvs", label: "Өлгий" },
      { value: "umnugovi-uvs", label: "Өмнөговь" },
      { value: "undurkhangai", label: "Өндөрхангай" },
      { value: "sagil", label: "Сагил" },
      { value: "tarialan-uvs", label: "Тариалан" },
      { value: "tes-uvs", label: "Тэс" },
      { value: "turgen", label: "Түргэн" },
      { value: "hovd-uvs", label: "Ховд" },
      { value: "khyargas", label: "Хяргас" },
      { value: "tsagaankhairkhan-uvs", label: "Цагаанхайрхан" },
    ],
  },
  {
    value: "khovd",
    label: "Ховд",
    sums: [
      { value: "jargalant-khovd", label: "Ховд (Жаргалант)" },
      { value: "altai-khovd", label: "Алтай" },
      { value: "bulgan-khovd", label: "Булган" },
      { value: "buyant-khovd", label: "Буянт" },
      { value: "darvi-khovd", label: "Дарви" },
      { value: "durgun", label: "Дөргөн" },
      { value: "duut", label: "Дуут" },
      { value: "zereg", label: "Зэрэг" },
      { value: "mankhan", label: "Манхан" },
      { value: "munkhkhairkhan", label: "Мөнххайрхан" },
      { value: "must", label: "Мөст" },
      { value: "myangad", label: "Мянгад" },
      { value: "uench", label: "Үенч" },
      { value: "khovd-khovd", label: "Ховд" },
      { value: "tsetseg", label: "Цэцэг" },
      { value: "chandmani-khovd", label: "Чандмань" },
      { value: "erdeneburen", label: "Эрдэнэбүрэн" },
    ],
  },
  {
    value: "khuvsgul",
    label: "Хөвсгөл",
    sums: [
      { value: "murun", label: "Мөрөн" },
      { value: "alag-erdene", label: "Алаг-Эрдэнэ" },
      { value: "arbulag", label: "Арбулаг" },
      { value: "bayanzurkh-khuvsgul", label: "Баянзүрх" },
      { value: "burentogtokh", label: "Бүрэнтогтох" },
      { value: "galt", label: "Галт" },
      { value: "jargalant-khuvsgul", label: "Жаргалант" },
      { value: "ikh-uul-khuvsgul", label: "Их-Уул" },
      { value: "rashaant-khuvsgul", label: "Рашаант" },
      { value: "renchinlkhumbe", label: "Рэнчинлхүмбэ" },
      { value: "tarialan-khuvsgul", label: "Тариалан" },
      { value: "tosontsengel-khuvsgul", label: "Тосонцэнгэл" },
      { value: "tumurbulag", label: "Төмөрбулаг" },
      { value: "tunel", label: "Түнэл" },
      { value: "ulaan-uul", label: "Улаан-Уул" },
      { value: "khankh", label: "Ханх" },
      { value: "tsagaannuur-khuvsgul", label: "Цагааннуур" },
      { value: "tsagaan-uul", label: "Цагаан-Уул" },
      { value: "tsagaan-uur", label: "Цагаан-Үүр" },
      { value: "tsetserleg-khuvsgul", label: "Цэцэрлэг" },
      { value: "chandmani-undur", label: "Чандмань-Өндөр" },
      { value: "shine-ider", label: "Шинэ-Идэр" },
      { value: "erdenebulgan-khuvsgul", label: "Эрдэнэбулган" },
    ],
  },
  {
    value: "khentii",
    label: "Хэнтий",
    sums: [
      { value: "kherlen-khentii", label: "Хэрлэн" },
      { value: "batnorov", label: "Батноров" },
      { value: "batshireet", label: "Батширээт" },
      { value: "bayan-adraga", label: "Баян-Адрага" },
      { value: "bayanmunkh", label: "Баянмөнх" },
      { value: "bayan-ovoo-khentii", label: "Баян-Овоо" },
      { value: "bayanhutag", label: "Баянхутаг" },
      { value: "binder", label: "Биндэр" },
      { value: "galshar", label: "Галшар" },
      { value: "dadal", label: "Дадал" },
      { value: "darkhan-khentii", label: "Дархан" },
      { value: "delgerkhaan-khentii", label: "Дэлгэрхаан" },
      { value: "jargaltkhaan", label: "Жаргалтхаан" },
      { value: "murun-khentii", label: "Мөрөн" },
      { value: "norovlin", label: "Норовлин" },
      { value: "umnudelger", label: "Өмнөдэлгэр" },
      { value: "tsenkhermandal", label: "Цэнхэрмандал" },
    ],
  },
]

// Нүүр хуудасны хайлтын хэсэгт ашиглах хялбарчилсан жагсаалт
export const locationData = [
  {
    value: "ulaanbaatar",
    label: "Улаанбаатар",
  },
  {
    value: "arkhangai",
    label: "Архангай",
  },
  {
    value: "bayan-ulgii",
    label: "Баян-Өлгий",
  },
  {
    value: "bayankhongor",
    label: "Баянхонгор",
  },
  {
    value: "bulgan",
    label: "Булган",
  },
  {
    value: "govi-altai",
    label: "Говь-Алтай",
  },
  {
    value: "govisumber",
    label: "Говьсүмбэр",
  },
  {
    value: "darkhan-uul",
    label: "Дархан-Уул",
  },
  {
    value: "dornogovi",
    label: "Дорноговь",
  },
  {
    value: "dornod",
    label: "Дорнод",
  },
  {
    value: "dundgovi",
    label: "Дундговь",
  },
  {
    value: "zavkhan",
    label: "Завхан",
  },
  {
    value: "orkhon",
    label: "Орхон",
  },
  {
    value: "uvurkhangai",
    label: "Өвөрхангай",
  },
  {
    value: "umnugovi",
    label: "Өмнөговь",
  },
  {
    value: "sukhbaatar-aimag",
    label: "Сүхбаатар",
  },
  {
    value: "selenge",
    label: "Сэлэнгэ",
  },
  {
    value: "tuv",
    label: "Төв",
  },
  {
    value: "uvs",
    label: "Увс",
  },
  {
    value: "khovd",
    label: "Ховд",
  },
  {
    value: "khuvsgul",
    label: "Хөвсгөл",
  },
  {
    value: "khentii",
    label: "Хэнтий",
  },
]
